apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: predictive-maintenance
      defaultBucket: sensor-scores
      tlsSkipVerify: true
    secureJsonData:
      token: my-token
    isDefault: true
    editable: true

  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      database: predictive_maintenance
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      postgresVersion: 1700
      timescaledb: false
    editable: true

  - name: MonitoringAPI
    type: grafana-simple-json-datasource
    access: proxy
    url: http://monitoring-api:8082/api
    editable: true
