---
apiVersion: v1
kind: Namespace
metadata:
  name: predictive-maintenance
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
  namespace: predictive-maintenance
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka.kafka.svc.cluster.local:9092"
  INFLUXDB_URL: "http://influxdb.monitoring.svc.cluster.local:8086"
  INFLUXDB_ORG: "cnc-org"
  INFLUXDB_BUCKET: "cnc-metrics"
  LOG_LEVEL: "INFO"
  EDGE_BASE_URL: "http://edge-agent.predictive-maintenance.svc.cluster.local:8000"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: predictive-maintenance
type: Opaque
stringData:
  postgres-url: "postgresql+asyncpg://cnc_user:cnc_password@postgres.predictive-maintenance.svc.cluster.local:5432/predictive_maintenance"
  postgres-jdbc-url: "jdbc:postgresql://postgres.predictive-maintenance.svc.cluster.local:5432/predictive_maintenance"
  postgres-user: "cnc_user"
  postgres-password: "cnc_password"
  influxdb-token: "cnc-token-secret"
